name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: mvn  -B -e -Dmaven.wagon.http.pool=false --settings settings.xml deploy -DskipTests
      env:
          GITHUB_USERNAME: harmanpa
          GITHUB_PASSWORD: ${{ secrets.GH }}
    - name: Job Failed Notification
      if: ${{ failure() }}
      uses: rtCamp/action-slack-notify@v2.1.2
      env:
        SLACK_CHANNEL: releases
        SLACK_COLOR: '#ff0000'
        SLACK_TITLE: 'Robotics Build Failed'
        SLACK_USERNAME: sdfbot
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        MSG_MINIMAL: commit
        SLACK_FOOTER: CAE Tech
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2.1.2
      env:
        SLACK_CHANNEL: releases
        SLACK_TITLE: 'New build of Robotics'
        SLACK_USERNAME: sdfbot
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        MSG_MINIMAL: commit
        SLACK_FOOTER: CAE Tech
